# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "950673910c321ccfd22148631248c96c"
name = "Verify COD Orders"
handle = "verify-codorders"
application_url = "https://codorders.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update", "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products,write_customers,write_orders"

[auth]
redirect_urls = ["https://codorders.fly.dev/auth/callback", "https://codorders.fly.dev/auth/shopify/callback", "https://codorders.fly.dev/api/auth/callback"]

[pos]
embedded = false
