# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "54dbd7dc86de2715d11c65d0934dcdd5"
name = "Verify COD Orders"
handle = "verify-cod-orders-3"
application_url = "https://dress-cleaners-coral-luke.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://dress-cleaners-coral-luke.trycloudflare.com/auth/callback", "https://dress-cleaners-coral-luke.trycloudflare.com/auth/shopify/callback", "https://dress-cleaners-coral-luke.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
